
CocktailRecipe.create!([
    {id: 44, title: "Echo Park", description: "The Echo Park is another one of those advanced mixologist cocktails that all you pros out there really need to try out.", directions: "Using a fruit peeler, create a long strip of orange peel and roll it up (use two if needed). Place in a serving glass and set aside.\r\nIn a mixing beaker, combine brandy, chile liqueur, Gran Classico Bitter, Amaro, Patchouli bitters and ice. Stir well.\r\nLightly torch the top of the orange peel garnish and pour in mix.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Echo-Park-300x300.jpg"},
    {id: 45, title: "Classic Mojito", description: "From Cuba, one of the best drinks ever created.", directions: "Drop lime wedges, mint leaves and simple syrup into base of glass. Muddle well.\r\nAdd ice and rum before topping with club soda.\r\nGarnish with a lime wedge and a mint sprig.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Classic-Mojito-300x300.jpg"},
    {id: 46, title: "Orange Mojito", description: "The classic mojito gets a phenomenal twist with this Orange Mojito recipe.", directions: "Add lime wedges, mint leaves and simple syrup to base of glass. Muddle.\r\nAdd ice and orange slices to glass and pour over white rum and fresh squeezed orange juice.\r\nTop with a splash of soda water and garnish with a mint sprig.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/OrangeMojitoThumb-300x300.jpg"},
    {id: 47, title: "Beachside Bonfire", description: "Sunset colored mixed drinks don't get much prettier than this Beachside Bonfire.", directions: "Rim a glass with corn syrup and brown sugar.\r\nBuild a glass with ice and pour in rums and pineapple juice.\r\nDrizzle some grenadine and top with a mini fruit skewer.\r\n", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Beachside-Bonfire-300x300.jpg"},
    {id: 48, title: "Island Main Squeeze", description: "Slushy layered cocktails don't get much more beautiful than this Island Main Squeeze.", directions: "In a blender with ice, combine coconut rum, mango rum, piña colada mix, mango puree, and mango slices. Blend thoroughly until smooth.\r\nIn a separate blender with ice, combine light rum, strawberry liqueur, strawberry daiquiri mix, and strawberries. Blend thoroughly until smooth.\r\nPour mixes into serving glass, alternating the layers and garnish with a mango slice and a cherry.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Island-Main-Squeeze-300x300.jpg"},
    {id: 49, title: "Dragon Fruit Sangria", description: "The Dragon Fruit Sangria is one of the biggest, boldest rum cocktails out there.", directions: "Scoop dragonfruit into the base of your glass and muddle well.\r\nAdd ice and lemon and orange slices.\r\nPour in dragonberry rum, rosé, lemonade, and pineapple juice.\r\nGarnish with an orange slice", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Dragon-Fruit-Sangria-300x300.jpg"},
    {id: 50, title: "Razzleberry Delight", description: "Dessert cocktail lovers need to try this Razzleberry Delight 'cause it's tasty beyond belief.", directions: "Combine ingredients in a blender and blend well.\r\nPour in mix into tall glass.\r\nTop with whipped cream and garnish with blackberries/raspberries.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/03/razzleberry-delight-300x300.jpg"},
    {id: 51, title: "Adios Jungle Juice", description: "Get the party super twisted with this crazy drink.", directions: "Add fruits to base of pitcher and pour over vodka, rum, gin, tequila, blue curaçao, sweet and sour and lemon lime soda. Stir well.", image_url: "https://tipsybartender.com/wp-content/uploads/2019/02/adios-jungle-juice-300x300.jpg"},
    {id: 52, title: "Trash Can", description: "Get trashed with a Trash Can.", directions: "Add ice to pint glass and pour over liquors. Insert a Red Bull can upside down on top.", image_url: "https://tipsybartender.com/wp-content/uploads/2019/10/the-ultimate-trash-can-300x300.jpg"},
    {id: 53, title: "Smirnoff Ice Blue Margarita", description: "Margarita made with Smirnoff Ice and Blue Curacao.", directions: "Rim edge of pint glass with lime juice and salt. Add a little ice and pour over tequila, blue curaçao and lime juice.\r\nAdd a bottle of Smirnoff Ice and garnish with a lime wedge.", image_url: "https://tipsybartender.com/wp-content/uploads/2019/12/smirnoff-ice-blue-margarita-300x300.jpg"},
    {id: 54, title: "Jack Frostie", description: "Blended icy cocktail that will get you chilled.", directions: "Add ice, coconut tequila, triple sec, sour mix and blue curaçao in blender and combine until smooth.\r\nRim edge of serving glass with coconut flakes and pour mix inside. Garnish with a lime slice.\r\n", image_url: "https://tipsybartender.com/wp-content/uploads/2019/11/jack-frostie-300x300.jpg"},
    {id: 55, title: "Wild Thing", description: "A wild cocktail.", directions: "Add ice, tequila, lime juice and cranberry juice to shaking glass and shake well.\r\nStrain mix over ice in rocks glass and top with soda water.\r\nGarnish with a lime wheel.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Wild-Thing-300x300.jpg"},
    {id: 56, title: "Blue Jamaican Long Island", description: "Long Island Tea with a caribbean twist.", directions: "Add ice to serving glass suspending blueberries throughout.\r\nPour clear liquors and sweet and sour into glass before drizzling blue curaçao on top. Top with dark rum.\r\nGarnish with a pineapple wedge.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Blue-Jamaican-Long-Island-300x300.jpg"},
    {id: 57, title: "Jalapeño Cucumber Margarita", description: "Try out this Jalapeño Cucumber Margarita if you love spicy cocktail recipes and twists on the classic margarita.", directions: "Rim edge of glass with salt and lime zest and set aside.\r\nMuddle cucumbers and jalapeños with agave syrup in base of glass. Add ice.\r\nPour over tequila and lime juice and shake well.\r\nAdd cucumber and ice throughout rimmed glass and strain mix over. Garnish with a cucumber slice.\r\n", image_url: "https://tipsybartender.com/wp-content/uploads/2018/02/jalapeno-cucumber-margarita-300x300.jpg"},
    {id: 65, title: "Blue Raspberry Jolly Rancher “Moonshine”", description: "Get messed up with this awesome jolly rancher moonshine.", directions: "Drop jolly rancher candies into base of mason jar and pour over everclear.\u2028\r\nAdd blue raspberry syrup and top with lemon lime soda.\u2028\r\nLet sit, shaking periodically until jolly ranchers have completely dissolved. Serve!\u2028", image_url: "https://tipsybartender.com/wp-content/uploads/2019/02/blue-raspberry-jolly-rancher-moonshine-300x300.jpg"},
    {id: 66, title: "Margarita Moonshine", description: "Like a Margarita only way stronger.", directions: "Combine sugar and water over low heat until dissolved. Leave to cool and add lemon and lime juice and salt. Stir and add Everclear.\r\nAdd mix to container and close tightly. Leave to infuse in the refrigerator for about two weeks. Serve.", image_url: "https://tipsybartender.com/wp-content/uploads/2019/02/blue-raspberry-jolly-rancher-moonshine-300x300.jpg"},
    {id: 67, title: "Apple Pie Moonshine", description: "Also called cowboy apple juice.", directions: "Combine apple cider, apple juice, sugar, cinnamon and nutmeg in a pot and simmer for at least an hour. Remove from heat.\r\nOnce cool, add everclear and strain into jar. For best flavor, store in refrigerator for a few weeks before serving.", image_url: "https://tipsybartender.com/wp-content/uploads/2019/11/apple-pie-moonshine-300x300.jpg"},
    {id: 68, title: "Adios Motherfucker", description: "You say goodbye, we say hello, and also, Adios Motherf*cker!", directions: "Fill a glass with ice and pour in vodka, rum, gin, tequila sweet & sour, lemon lime soda and blue curaçao. Stir to mix.\r\nGarnish with a lemon slice and a cherry.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Adios-Motherfcker-300x300.jpg"},
    {id: 69, title: "Day Of The Dead Watermelon Margarita", description: "Here it is people, the legendary Day Of The Dead Watermelon Margarita.", directions: "Carve mini watermelon with sugar skull design. Remove the top and scoop out watermelon.\r\nAdd watermelon to blender with tequila, lime juice, simple syrup and ice. Combine well.\r\nPour mix back inside watermelon and serve.\r\n", image_url: "https://tipsybartender.com/wp-content/uploads/2018/10/day-of-the-dead-watermelon-margarita-300x300.jpg"},
    {id: 70, title: "H-Bomb", description: "This H-Bomb drink is one of those Hpnotiq and vodka drink recipes that's super refreshing and super potent.", directions: "Combine ingredients in a shaker with ice and shake well.\r\nStrain mix into a glass over ice and garnish with a cherry.", image_url: "https://i.pinimg.com/236x/ae/11/c4/ae11c459ead80651237ddb4f76404ecf.jpg"},
    {id: 71, title: "Long Island Iced Tea", description: "The classic Long Island Iced Tea.", directions: "Add ice to tall glass before pouring over tequila, vodka, rum, gin, triple sec and sweet and sour.\r\nTop with a splash of cola and garnish with a lime wheel and mint sprig.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Long-Island-Iced-Tea-300x300.jpg"},
    {id: 72, title: "Bourbon Basil Berry Bash ", description: "A very nice drink for the summer.", directions: "Add lemon juice, simple syrup and berries and basil to base of glass and muddle. Add ice and bourbon and triple sec. Shake well.\r\nStrain mix over ice in tumbler glass and top with soda water.\r\nGarnish with a basil leaf and berry skewer resting on top.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/09/bourbon-basil-berry-bash-300x300.jpg"},
    {id: 73, title: "AK 47 Cocktail", description: "Those who're not looking to get wasted better take cover 'cause what we have here is the AK-47 Cocktail.", directions: "Fill a glass with ice and pour in brandy, whiskey, gin, vodka, rum, bourbon, and Cointreau.\r\nAdd lime juice and top with soda water. Stir well.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/AK-47-Cocktail-300x300.jpg"},
    {id: 74, title: "Winter Solstice", description: "Great Martini for the winter.", directions: "Combine Amaro, bourbon, sweet vermouth, and walnut bitters in a mixing glass with ice and stir.\r\nStrain mix into a martini glass and express a flaming lemon peel.\r\nRim the glass with the lemon peel and drop in for garnish.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/03/winter-solstice-300x300.jpg"},
    {id: 75, title: "Green Jungle Juice Shots", description: "Ladies and gentlemen, these Green Jungle Juice Shots are really something else.", directions: "Drop fruits in base of pitcher and pour over liquors and mixers. Stir well.\r\nServe in shot glasses, garnished with an orange wedge.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Green-Jungle-Juice-Shots-300x300.jpg"},
    {id: 76, title: "Aqua Hurricane", description: "You want to get rocked like a hurricane?", directions: "Rim edge of glass with blue sugar. Set aside.\r\nIn an ice filled glass combine melon liqueur and simple syrup. Stir well. Pour into base of glass and top with ice. Add lemon lime soda.\r\nIn an ice filled glass mix strawberry vodka and blue curacao and float on top.\r\nGarnish with cherry.\r\n", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Aqua-Hurricane-300x300.jpg"},
    {id: 77, title: "Bulldog Fishbowl", description: "We challenge you to make a Bulldog Fishbowl, one of the most intense tequila cocktails we can think of. Plus this bad boy has coconut tequila, orange juice, fresh squeezed lime, and of course, a couple of bottles of Corona. Which means if you want to make an outlandish lager cocktail, this bowl has you covered there too.", directions: "We challenge you to make a Bulldog Fishbowl, one of the most intense tequila cocktails we can think of. Plus this bad boy has coconut tequila, orange juice, fresh squeezed lime, and of course, a couple of bottles of Corona. Which means if you want to make an outlandish lager cocktail, this bowl has you covered there too.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/bulldog-fishbowl-300x300.jpg"},
    {id: 86, title: "Dutch Mojito", description: "This Dutch Mojito is one of the tastiest twists on the classic Mojito ever made, trust us.", directions: "To base of glass add lime wedges, mint leaves and brown sugar. Muddle.\r\nAdd ice to glass and pour over jenever gin and simple syrup. Stir lightly.\r\nTop with sparkling water and garnish with a mint sprig.", image_url: "https://tipsybartender.com/wp-content/uploads/2018/01/Dutch-Mojito-300x300.jpg"},
    {id: 87, title: "Blue Raspberry Mojito", description: "Change up the classic mojito with this Blue Raspberry Mojito and you'll be feeling #blessed.", directions: "Muddle mint leaves, lime wedges and simple syrup in base of glass. Add ice.\r\nAdd ice to tall glass, adding mint leaves and raspberries throughout.\r\nour Pour rum, raspberry vodka, and club soda.\r\nDrizzle Blue Curaçao and garnish with mint leaves and raspberries.", image_url: "https://tipsybartender.com/wp-content/uploads/2019/01/blue-raspberry-mojito-300x300.jpg"}
  ]) 


Ingredient.create!([
  {cocktail_recipe_id: 47, name: "Pineapple Juice"},
  {cocktail_recipe_id: 55, name: "Lime Juice"}, 
  {cocktail_recipe_id: 57, name: "Lime Juice"}, 
  {cocktail_recipe_id: 53, name: "Lime Juice"}, 
  {cocktail_recipe_id: 69, name: "Lime Juice"}, 
  {cocktail_recipe_id: 87, name: "Lime Juice"}, 
  {cocktail_recipe_id: 66, name: "Lime Juice"},  
  {cocktail_recipe_id: 77, name: "Orange Juice"}, 
  {cocktail_recipe_id: 75, name: "Orange Juice"},
  {cocktail_recipe_id: 56, name: "Gin"}, 
  {cocktail_recipe_id: 52, name: "Gin"}, 
  {cocktail_recipe_id: 68, name: "Gin"}, 
  {cocktail_recipe_id: 70, name: "Gin"}, 
  {cocktail_recipe_id: 71, name: "Gin"}, 
  {cocktail_recipe_id: 75, name: "Gin"}, 
  {cocktail_recipe_id: 86, name: "Gin"}, 
  {cocktail_recipe_id: 73, name: "Gin"},  
  {cocktail_recipe_id: 73, name: "Brandy"}, 
  {cocktail_recipe_id: 44, name: "Brandy"}, 
  {cocktail_recipe_id: 44, name: "Whiskey"},
  {cocktail_recipe_id: 70, name: "Vodka"},
  {cocktail_recipe_id: 71, name: "Vodka"},
  {cocktail_recipe_id: 72, name: "Bourbon Whiskey"},
  {cocktail_recipe_id: 87, name: "Rum"}, 
  {cocktail_recipe_id: 75, name: "Rum"},
  {cocktail_recipe_id: 70, name: "Rum"}, 
  {cocktail_recipe_id: 71, name: "Rum"}, 
  {cocktail_recipe_id: 72, name: "Triple Sec"},
  {cocktail_recipe_id: 70, name: "Triple Sec"},
  {cocktail_recipe_id: 72, name: "Simple Syrup"}, 
  {cocktail_recipe_id: 45, name: "Simple Syrup"}, 
  {cocktail_recipe_id: 69, name: "Simple Syrup"}, 
  {cocktail_recipe_id: 86, name: "Simple Syrup"},
  {cocktail_recipe_id: 44, name: "Amaro"}, 
  {cocktail_recipe_id: 74, name: "Amaro"}, 
  {cocktail_recipe_id: 74, name: "Sweet Vermouth"},
  {cocktail_recipe_id: 74, name: "Black Walnut Bitters"},
  {cocktail_recipe_id: 44, name: "Chile Liqueur"},
  {cocktail_recipe_id: 44, name: "Gran Classico Bitter"},
  {cocktail_recipe_id: 44, name: "Patchouli Bitters"},
  {cocktail_recipe_id: 44, name: "Torched Orange Peel Garnish"},
  {cocktail_recipe_id: 45, name: "Lime Wedges"}, 
  {cocktail_recipe_id: 86, name: "Lime Wedges"},
  {cocktail_recipe_id: 87, name: "Club Soda"},
  {cocktail_recipe_id: 72, name: "Club Soda"},
  {cocktail_recipe_id: 45, name: "Mint Leaves"}, 
  {cocktail_recipe_id: 86, name: "Mint Leaves"}, 
  {cocktail_recipe_id: 46, name: "Mint Leaves"},
  {cocktail_recipe_id: 48, name: "White Rum"}, 
  {cocktail_recipe_id: 46, name: "White Rum"}, 
  {cocktail_recipe_id: 46, name: "Fresh Orange Juice"},
  {cocktail_recipe_id: 46, name: "Pineapple Rum"},
  {cocktail_recipe_id: 48, name: "Mango Rum"},
  {cocktail_recipe_id: 75, name: "Coconut Rum"},
  {cocktail_recipe_id: 48, name: "Coconut Rum"},
  {cocktail_recipe_id: 48, name: "Piña Colada Mix"},
  {cocktail_recipe_id: 48, name: "Mango Puree"},
  {cocktail_recipe_id: 48, name: "Strawberry Liqueur"},
  {cocktail_recipe_id: 48, name: "Strawberry Daiquiri Mix"},
  {cocktail_recipe_id: 49, name: "Lemonade"},
  {cocktail_recipe_id: 49, name: "Dragonberry Rum"},
  {cocktail_recipe_id: 49, name: "Dragon Fruit"},
  {cocktail_recipe_id: 49, name: "Lemon Slices"},
  {cocktail_recipe_id: 49, name: "Orange Slices"},
  {cocktail_recipe_id: 50, name: "Raspberry Liqueur"},
  {cocktail_recipe_id: 50, name: "Cream of Coconut"},
  {cocktail_recipe_id: 50, name: "Razzmatazz Schnapps"},
  {cocktail_recipe_id: 50, name: "Fresh Lime Juice"},
  {cocktail_recipe_id: 50, name: "Blackberries"},
  {cocktail_recipe_id: 69, name: "Tequila"}, 
  {cocktail_recipe_id: 75, name: "Tequila"}, 
  {cocktail_recipe_id: 57, name: "Tequila"},
  {cocktail_recipe_id: 87, name: "Blue Curaçao"}, 
  {cocktail_recipe_id: 54, name: "Blue Curaçao"},
  {cocktail_recipe_id: 70, name: "Sweet & Sour Mix"}, 
  {cocktail_recipe_id: 71, name: "Sweet & Sour Mix"}, 
  {cocktail_recipe_id: 76, name: "Lemon Lime Soda"}, 
  {cocktail_recipe_id: 51, name: "Lemon Lime Soda"}, 
  {cocktail_recipe_id: 52, name: "Red Bull"},
  {cocktail_recipe_id: 77, name: "Coconut Tequila"},
  {cocktail_recipe_id: 54, name: "Sour Mix"},
  {cocktail_recipe_id: 52, name: "Cranberry Juice"},
  {cocktail_recipe_id: 57, name: "Agave Syrup"},
  {cocktail_recipe_id: 57, name: "Sliced Jalapeños"},
  {cocktail_recipe_id: 57, name: "Cucumbers"},
  {cocktail_recipe_id: 65, name: "Lemon Soda"},
  {cocktail_recipe_id: 65, name: "Blue Raspberry Syrup"},
  {cocktail_recipe_id: 65, name: "Blue Raspberry Jolly Ranchers"},
  {cocktail_recipe_id: 75, name: "Everclear"}, 
  {cocktail_recipe_id: 66, name: "Everclear"}, 
  {cocktail_recipe_id: 66, name: "Water"},
  {cocktail_recipe_id: 66, name: "Sugar"},
  {cocktail_recipe_id: 66, name: "Lemon Juice"},
  {cocktail_recipe_id: 66, name: "Salt"},
  {cocktail_recipe_id: 67, name: "Apple Juice"},
  {cocktail_recipe_id: 67, name: "Apple Cider"},
  {cocktail_recipe_id: 67, name: "Cinnamon Sticks"},
  {cocktail_recipe_id: 67, name: "Nutmeg"},
  {cocktail_recipe_id: 69, name: "Watermelon Chunks"},
  {cocktail_recipe_id: 72, name: "Basil Leaves"},
  {cocktail_recipe_id: 76, name: "Strawberry"},
  {cocktail_recipe_id: 76, name: "Cointreau"},
  {cocktail_recipe_id: 76, name: "Strawberry Vodka"},
  {cocktail_recipe_id: 76, name: "Melon Liqueur"},
  {cocktail_recipe_id: 77, name: "Margarita Mix"},
  {cocktail_recipe_id: 77, name: "Corona Bottles"},
  {cocktail_recipe_id: 77, name: "Limes"},
  {cocktail_recipe_id: 86, name: "Brown Sugar"},
  {cocktail_recipe_id: 87, name: "Raspberry Vodka"},
  {cocktail_recipe_id: 87, name: "Raspberries"}
]) 




